const fs = require('fs')

const lines = []
lines.push("import { useState } from 'react'")
lines.push("import { WaterCard } from './components/WaterCard'")
lines.push("import { AmbienteCard } from './components/AmbienteCard'")
lines.push("import { SustratoCard } from './components/SustratoCard'")
lines.push("")
lines.push("const tanques = [")
lines.push("  { nombre: 'Sala Madre', fecha: '2026-06-01', ph: 6.2, ec: 1.4, ppm: 700, temperatura: 22, orp: 380 },")
lines.push("  { nombre: 'Sala Flor', fecha: '2026-05-15', ph: 6.5, ec: 1.8, ppm: 900, temperatura: 23, orp: 350 },")
lines.push("  { nombre: 'Sala Clones', fecha: '2026-06-08', ph: 5.9, ec: 0.8, ppm: 400, temperatura: 21, orp: 420 },")
lines.push("]")
lines.push("")
lines.push("const salas = [")
lines.push("  { nombre: 'Sala Madre', etapa: 'vegetativo', temperatura: 24, humedad: 60, co2: null },")
lines.push("  { nombre: 'Sala Flor', etapa: 'floracion', temperatura: 26, humedad: 88, co2: 1200 },")
lines.push("  { nombre: 'Sala Clones', etapa: 'clones', temperatura: 23, humedad: 70, co2: null },")
lines.push("] as const")
lines.push("")
lines.push("const grupos = [")
lines.push("  { nombre: 'Tropical Runtz - Tanda 2', etapa: 'floracion', cantidadPlantas: 6, temperatura: 21, humedad: 45, ph: 6.1, ec: 1.6, runoffPh: 6.3, runoffEc: 1.9 },")
lines.push("  { nombre: 'Carlson Phenotype A', etapa: 'vegetativo', cantidadPlantas: 4, temperatura: 23, humedad: 55, ph: 5.9, ec: 1.2, runoffPh: 6.0, runoffEc: 1.3 },")
lines.push("] as const")
lines.push("")
lines.push("const navTabs = [")
lines.push("  { id: 'agua', label: 'Solucion de riego' },")
lines.push("  { id: 'ambiente', label: 'Ambiente' },")
lines.push("  { id: 'plantas', label: 'Cultivares' },")
lines.push("]")
lines.push("")
lines.push("function App() {")
lines.push("  const [tab, setTab] = useState('agua')")
lines.push("")
lines.push("  return (")
lines.push("    <div className='min-h-screen bg-gray-950 text-white'>")
lines.push("      <header className='bg-gray-900 border-b border-green-900 px-6 py-4'>")
lines.push("        <h1 className='text-2xl font-bold text-green-400'>CultivOS</h1>")
lines.push("        <p className='text-gray-400 text-sm'>Cannabis Co-Pilot</p>")
lines.push("      </header>")
lines.push("")
lines.push("      <nav className='flex gap-2 px-6 py-3 bg-gray-900 border-b border-gray-800'>")
lines.push("        {navTabs.map((t) => (")
lines.push("          <button")
lines.push("            key={t.id}")
lines.push("            onClick={() => setTab(t.id)}")
lines.push("            className={'px-4 py-1.5 rounded text-sm font-medium ' + (tab === t.id ? 'bg-green-600 text-white' : 'text-gray-400 hover:text-white')}")
lines.push("          >")
lines.push("            {t.label}")
lines.push("          </button>")
lines.push("        ))}")
lines.push("      </nav>")
lines.push("")
lines.push("      <main className='p-6'>")
lines.push("        {tab === 'agua' && tanques.map((t) => <WaterCard key={t.nombre} {...t} />)}")
lines.push("        {tab === 'ambiente' && salas.map((s) => <AmbienteCard key={s.nombre} {...s} />)}")
lines.push("        {tab === 'plantas' && grupos.map((g) => <SustratoCard key={g.nombre} {...g} />)}")
lines.push("      </main>")
lines.push("    </div>")
lines.push("  )")
lines.push("}")
lines.push("")
lines.push("export default App")

const code = lines.join('\n')
fs.writeFileSync('src/App.tsx', code, { encoding: 'utf8' })
console.log('OK - App escrito, ' + lines.length + ' lineas')