const fs = require('fs')

const lines = []
lines.push("import { useState } from 'react'")
lines.push("import { WaterCard } from './components/WaterCard'")
lines.push("import { AmbienteCard } from './components/AmbienteCard'")
lines.push("import { SustratoCard } from './components/SustratoCard'")
lines.push("import { GeneticaCard } from './components/GeneticaCard'")
lines.push("import { Dashboard } from './components/Dashboard'")
lines.push("import { NuevoCultivoForm } from './components/NuevoCultivoForm'")
lines.push("")
lines.push("const misGeneticas = [")
lines.push("  { id: 'g1', nombre: 'Tropical Runtz' },")
lines.push("  { id: 'g2', nombre: 'Carlson Phenotype A' },")
lines.push("]")
lines.push("")
lines.push("const cultivosBaseInicial = [")
lines.push("  { id: 'flor1', nombre: 'Sala Flor', etapa: 'floracion' },")
lines.push("  { id: 'madre1', nombre: 'Sala Madre', etapa: 'vegetativo' },")
lines.push("  { id: 'clones1', nombre: 'Sala Clones', etapa: 'clones' },")
lines.push("]")
lines.push("")
lines.push("const datosAguaInicial: Record<string, any> = {")
lines.push("  flor1: { nombre: 'Sala Flor', fecha: '2026-05-15', ph: 6.5, ec: 1.8, ppm: 900, temperatura: 23, orp: 350 },")
lines.push("  madre1: { nombre: 'Sala Madre', fecha: '2026-06-01', ph: 6.2, ec: 1.4, ppm: 700, temperatura: 22, orp: 380 },")
lines.push("  clones1: { nombre: 'Sala Clones', fecha: '2026-06-08', ph: 5.9, ec: 0.8, ppm: 400, temperatura: 21, orp: 420 },")
lines.push("}")
lines.push("")
lines.push("const datosAmbienteInicial: Record<string, any> = {")
lines.push("  flor1: { nombre: 'Sala Flor', etapa: 'floracion', temperatura: 26, humedad: 88, co2: 1200 },")
lines.push("  madre1: { nombre: 'Sala Madre', etapa: 'vegetativo', temperatura: 24, humedad: 60, co2: null },")
lines.push("  clones1: { nombre: 'Sala Clones', etapa: 'clones', temperatura: 23, humedad: 70, co2: null },")
lines.push("}")
lines.push("")
lines.push("const datosSustratoInicial: Record<string, any[]> = {")
lines.push("  flor1: [{ nombre: 'Tropical Runtz - Tanda 2', etapa: 'floracion', cantidadPlantas: 6, temperatura: 21, humedad: 45, ph: 6.1, ec: 1.6, runoffPh: 6.3, runoffEc: 1.9 }],")
lines.push("  madre1: [{ nombre: 'Carlson Phenotype A', etapa: 'vegetativo', cantidadPlantas: 4, temperatura: 23, humedad: 55, ph: 5.9, ec: 1.2, runoffPh: 6.0, runoffEc: 1.3 }],")
lines.push("  clones1: [{ nombre: 'Clones varios', etapa: 'clones', cantidadPlantas: 12, temperatura: 23, humedad: 70, ph: 5.8, ec: 0.7, runoffPh: 5.9, runoffEc: 0.8 }],")
lines.push("}")
lines.push("")
lines.push("const datosGeneticaInicial: Record<string, any[]> = {")
lines.push("  flor1: [{")
lines.push("    descripcion: 'Tropical Runtz - Tanda 2',")
lines.push("    cantidadPlantas: 6,")
lines.push("    fechaInicio: '2026-05-01',")
lines.push("    intervenciones: [")
lines.push("      { tipo: 'trasplante', fecha: '2026-05-10', detalle: 'Maceta 11L' },")
lines.push("      { tipo: 'poda', fecha: '2026-06-01', detalle: 'Defoliacion' },")
lines.push("      { tipo: 'producto', fecha: '2026-06-12', detalle: 'PK boost 2ml/L' },")
lines.push("    ],")
lines.push("  }],")
lines.push("  madre1: [{")
lines.push("    descripcion: 'Carlson Phenotype A',")
lines.push("    cantidadPlantas: 4,")
lines.push("    fechaInicio: '2026-04-01',")
lines.push("    intervenciones: [")
lines.push("      { tipo: 'trasplante', fecha: '2026-04-15', detalle: 'Maceta 7L' },")
lines.push("      { tipo: 'poda', fecha: '2026-05-20', detalle: 'Apical' },")
lines.push("    ],")
lines.push("  }],")
lines.push("  clones1: [{")
lines.push("    descripcion: 'Clones varios',")
lines.push("    cantidadPlantas: 12,")
lines.push("    fechaInicio: '2026-06-05',")
lines.push("    intervenciones: [")
lines.push("      { tipo: 'trasplante', fecha: '2026-06-05', detalle: 'Vasos 200ml' },")
lines.push("    ],")
lines.push("  }],")
lines.push("}")
lines.push("")
lines.push("const navTabs = [")
lines.push("  { id: 'ambiente', label: 'Ambiente' },")
lines.push("  { id: 'agua', label: 'Solucion de riego' },")
lines.push("  { id: 'plantas', label: 'Cultivares' },")
lines.push("]")
lines.push("")
lines.push("function App() {")
lines.push("  const [vista, setVista] = useState<'dashboard' | 'cultivo' | 'nuevo-cultivo'>('dashboard')")
lines.push("  const [cultivoId, setCultivoId] = useState<string | null>(null)")
lines.push("  const [tab, setTab] = useState('ambiente')")
lines.push("")
lines.push("  const [cultivosBase, setCultivosBase] = useState(cultivosBaseInicial)")
lines.push("  const [datosAgua, setDatosAgua] = useState(datosAguaInicial)")
lines.push("  const [datosAmbiente, setDatosAmbiente] = useState(datosAmbienteInicial)")
lines.push("  const [datosSustrato, setDatosSustrato] = useState(datosSustratoInicial)")
lines.push("  const [datosGenetica, setDatosGenetica] = useState(datosGeneticaInicial)")
lines.push("")
lines.push("  function abrirCultivo(id: string) {")
lines.push("    setCultivoId(id)")
lines.push("    setTab('ambiente')")
lines.push("    setVista('cultivo')")
lines.push("  }")
lines.push("")
lines.push("  function volverADashboard() {")
lines.push("    setVista('dashboard')")
lines.push("    setCultivoId(null)")
lines.push("  }")
lines.push("")
lines.push("  function guardarNuevoCultivo(datos: { nombre: string; etapa: string; fechaInicio: string; cantidadPlantas: number; geneticaId: string }) {")
lines.push("    const id = 'cultivo-' + Date.now()")
lines.push("    const genetica = misGeneticas.find((g) => g.id === datos.geneticaId)")
lines.push("")
lines.push("    setCultivosBase((prev) => [...prev, { id, nombre: datos.nombre, etapa: datos.etapa }])")
lines.push("    setDatosAmbiente((prev) => ({ ...prev, [id]: { nombre: datos.nombre, etapa: datos.etapa, temperatura: 24, humedad: 60, co2: null } }))")
lines.push("    setDatosAgua((prev) => ({ ...prev, [id]: { nombre: datos.nombre, fecha: datos.fechaInicio, ph: 6.0, ec: 1.0, ppm: 500, temperatura: 22, orp: 400 } }))")
lines.push("    setDatosSustrato((prev) => ({ ...prev, [id]: [{ nombre: genetica ? genetica.nombre : datos.nombre, etapa: datos.etapa, cantidadPlantas: datos.cantidadPlantas, temperatura: 22, humedad: 60, ph: 6.0, ec: 1.0, runoffPh: 6.0, runoffEc: 1.0 }] }))")
lines.push("    setDatosGenetica((prev) => ({ ...prev, [id]: [{ descripcion: genetica ? genetica.nombre : datos.nombre, cantidadPlantas: datos.cantidadPlantas, fechaInicio: datos.fechaInicio, intervenciones: [] }] }))")
lines.push("")
lines.push("    abrirCultivo(id)")
lines.push("  }")
lines.push("")
lines.push("  if (vista === 'nuevo-cultivo') {")
lines.push("    return (")
lines.push("      <div className='min-h-screen bg-gray-950 text-white py-10'>")
lines.push("        <NuevoCultivoForm")
lines.push("          geneticasDisponibles={misGeneticas}")
lines.push("          onGuardar={guardarNuevoCultivo}")
lines.push("          onCargarGenetica={() => alert('Cargar genetica: proximamente')}")
lines.push("        />")
lines.push("      </div>")
lines.push("    )")
lines.push("  }")
lines.push("")
lines.push("  if (vista === 'dashboard') {")
lines.push("    return (")
lines.push("      <Dashboard")
lines.push("        cultivos={cultivosBase}")
lines.push("        onSelectCultivo={abrirCultivo}")
lines.push("        onNuevoCultivo={() => setVista('nuevo-cultivo')}")
lines.push("      />")
lines.push("    )")
lines.push("  }")
lines.push("")
lines.push("  const cultivo = cultivosBase.find((c) => c.id === cultivoId)")
lines.push("")
lines.push("  return (")
lines.push("    <div className='min-h-screen bg-gray-950 text-white'>")
lines.push("      <header className='bg-gray-900 border-b border-green-900 px-6 py-4 flex items-center gap-4'>")
lines.push("        <button onClick={volverADashboard} className='text-gray-400 hover:text-white text-sm'>")
lines.push("          back")
lines.push("        </button>")
lines.push("        <div>")
lines.push("          <h1 className='text-2xl font-bold text-green-400'>{cultivo ? cultivo.nombre : ''}</h1>")
lines.push("          <p className='text-gray-400 text-sm'>CultivOS - Cannabis Co-Pilot</p>")
lines.push("        </div>")
lines.push("      </header>")
lines.push("")
lines.push("      <nav className='flex gap-2 px-6 py-3 bg-gray-900 border-b border-gray-800'>")
lines.push("        {navTabs.map((t) => (")
lines.push("          <button")
lines.push("            key={t.id}")
lines.push("            onClick={() => setTab(t.id)}")
lines.push("            className={'px-4 py-1.5 rounded text-sm font-medium ' + (tab === t.id ? 'bg-green-600 text-white' : 'text-gray-400 hover:text-white')}")
lines.push("          >")
lines.push("            {t.label}")
lines.push("          </button>")
lines.push("        ))}")
lines.push("      </nav>")
lines.push("")
lines.push("      <main className='p-6'>")
lines.push("        {tab === 'ambiente' && cultivoId && <AmbienteCard {...datosAmbiente[cultivoId]} />}")
lines.push("        {tab === 'agua' && cultivoId && <WaterCard {...datosAgua[cultivoId]} />}")
lines.push("        {tab === 'plantas' && cultivoId && datosGenetica[cultivoId].map((g: any, i: number) => (")
lines.push("          <div key={i}>")
lines.push("            <GeneticaCard {...g} onNuevaIntervencion={() => alert('Registrar intervencion: proximamente')} />")
lines.push("            <SustratoCard {...datosSustrato[cultivoId][i]} />")
lines.push("          </div>")
lines.push("        ))}")
lines.push("      </main>")
lines.push("    </div>")
lines.push("  )")
lines.push("}")
lines.push("")
lines.push("export default App")

const code = lines.join('\n')
fs.writeFileSync('src/App.tsx', code, { encoding: 'utf8' })
console.log('OK - App escrito, ' + lines.length + ' lineas')